version: '3'
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /opt/plexmediaserver/tautulli:/config
    environment:
      - TZ=America/New_York
    ports:
      - 8181:8181