version: '3.4'

services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
      MEMORY: "4G"
      USER_UID: "1000"
      USER_GID: "1000"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /opt/games/minecraft/vanilla:/data
  tekxit:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.12.2"
      FORGEVERSION: "14.23.5.2860"
      #USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
      MEMORY: "10G"
      USER_UID: "1000"
      USER_GID: "1000"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /opt/games/minecraft/tekxit:/data
  josh:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: "1.19.1"
      TYPE: FABRIC
      USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
      MEMORY: "5G"
      USER_UID: "1000"
      USER_GID: "1000"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /opt/games/minecraft/josh:/data
  kate:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.12.2"
      FORGEVERSION: "14.23.5.2860"
      USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
      MEMORY: "4G"
      USER_UID: "1000"
      USER_GID: "1000"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /opt/games/minecraft/forge:/data
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    restart: unless-stopped
    environment:
      # enable API
      API_BINDING: ":25564"
    ports:
      - 25565:25565
      # bind the API port to only loopback to avoid external exposure
      - 127.0.0.1:25564:25564
    command: --mapping=[REDACTED]=vanilla:25565,[REDACTED]=kate:25565,[REDACTED]=josh:25565,[REDACTED]=tekxit:25565